# Mysql
aws:
    paramstore:
        enabled:
          true
        prefix:
          /config
        profile-seperator:
          _
        name:
          ebang
spring:
  config:
    import:
      'aws-parameterstore:'

    datasource:
      url:
        jdbc:mysql://cherrypicker-database.cfxpmyxyy9qj.ap-northeast-2.rds.amazonaws.com:3306/cherrypicker_database?characterEncoding=utf8
      username:
        admin
      password:
        cherrypcik3r

    jpa:
      show-sql:
        true
      database:
        mysql
      properties:
        hibernate:
          format_sql:
            true
          show_sql:
            true
          ddl-auto:
            update
    profiles:
      include:
        oauth-key

# oauth kakao
client:
    id:
      kakao:
        90f0b36bd37367b113a494fce6834618
      google:
        387913665744-i5timehl8mg38shj25p1pjd2g2hfe9ls:apps:googleusercontent:com
redirect:
    uri:
      kakao:
        http://43.202.25.158:8080/api/v1/auth/kakao/callback
      google:
        http://43.202.25.158:8080/api/v1/auth/google/callback

# oauth google
secret:
  google:
    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
test:
    test-yaml