# Mysql
aws:
    paramstore:
        enabled:
          true
        prefix:
          /config
        profile-seperator:
          _
        name:
          ebang
spring:
    import:
      'aws-parameterstore:'

    datasource:
      url:
        ${{secrets.DATASOURCE_URL}}
      username:
        ${{secrets.DATASOURCE_USERNAME}}
      password:
        ${{secrets.DATASOURCE_PASSWORD}}

    jpa:
      show-sql:
        true
      database:
        mysql
      properties:
        hibernate:
          format_sql:
            true
          show_sql:
            true
          ddl-auto:
            update
    profiles:
      include:
        oauth-key

# oauth kakao
client:
    id:
      kakao:
        ${{secrets.CLIENT_ID_KAKAO}}
      google:
        ${{secrets.CLIENT_ID_GOOGLE}}
redirect:
    uri:
      kakao:
        ${{secrets.REDIRECT_URI_KAKAO}}
      google:
        ${{secrets.REDIRECT_URI_GOOGLE}}

# oauth google
secret:
  google:
      ${{secrets.SECRET_GOOGLE}}
test:
    test-yaml