# Mysql
aws:
  paramstore:
    enabled:
      true
    prefix:
      /config
    profile-seperator:
      _
    name:
      ebang
spring:
  config:
    activate:
        profile:
          production
    import:
      'aws-parameterstore:'

  datasource:
    url:
      ${DATASOURCE_URL}
    username:
      ${DATASOURCE_USERNAME}
    password:
      ${DATASOURCE_PASSWORD}

  jpa:
    show-sql:
      true
    database:
      mysql
    properties:
      hibernate:
        format_sql:
          true
        show_sql:
          true
        ddl-auto:
          update
  profiles:
    include:
      oauth-key

# oauth kakao
client:
  id:
    kakao:
      ${CLIENT_ID_KAKAO}
    google:
      ${CLIENT_ID_GOOGLE}
redirect:
  uri:
    kakao:
      ${REDIRECT_URI_KAKAO}
    google:
      ${REDIRECT_URI_GOOGLE}

# oauth google
secret:
  google:
    ${SECRET_GOOGLE}
test:
  test-yaml
