# This is a basic workflow to help you get started with Actions

name: build test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "release" branch
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
 TEST_FILE: /src/main/java/com/cherrypicker/cherrypick3r/test/controller/testfile.yml
 CHANGE_WORD: yaml!
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell

      
      - name: Set testfile
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.TEST_FILE }}
        env:
          why: ${{env.CHANGE_WORD}}
          wh2: ${{env.CHANGE_WORD}}
      
      - name : echo commands
        run: echo 'done!'
